service: ses-bounce
frameworkVersion: '2'

custom:
  dynamoDbTableName: 'ses-bounce'
  deploymentBucketName: 'hyiromori-temp'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: "${self:custom.deploymentBucketName}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
      Resource:
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamoDbTableName}"

functions:
  api:
    handler: handlers/api.handler
    events:
      - http:
          path: ''
          method: post
  receiveBounse:
    handler: handlers/receive_bounce.handler

resources:
  Resources:
    bounceTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "${self:custom.dynamoDbTableName}"
        AttributeDefinitions:
          - AttributeName: "address"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "address"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
